services:
  web:
    image: tvi02/secdev-app:95d01dc6b25c5eda272c542ce9f06c889f2a9f9f
    container_name: secdev-seed-web
    ports:
      - "8000:8000"
    environment:
      APP_NAME: ${APP_NAME:-secdev-seed}
      DEBUG: ${DEBUG:-true}

    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request as u; u.urlopen('http://127.0.0.1:8000/').read()\""]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

    cap_drop: ["ALL"]
    security_opt:
      - no-new-privileges:true

    restart: unless-stopped
